## Filament Rich Editor Toolkit (asignua/filament-rich-editor-toolkit)

- Five independent pieces for the Filament 5 `RichEditor`: `PasteCleanPlugin`, `CustomAttributesPlugin`, `EmbedPlugin`, `ImageUrlPlugin` (all `Asignua\RichEditorToolkit\Plugins\*`, added with `RichEditor::make()->plugins([X::make()])`) and the panel plugin `Asignua\RichEditorToolkit\StickyToolbarPlugin`.
- A toolbar button exists only when it is listed in `->toolbarButtons([...])`: `cleanFormat`, `embed`, `imageUrl`. An unknown button name makes Filament throw.
- Run `php artisan filament:assets` after install/upgrade: the editor imports `resources/dist/*.js` by URL. A missing publish is a 404 and a silent `console.error`, the module is simply absent.
- Plugins with a server half (`CustomAttributesPlugin`, `EmbedPlugin`) MUST also be in the front-end renderer, otherwise the data sits in the database and vanishes on the page: render with `RichEditorToolkit::renderer($content)->toHtml()`, or add `RichEditorToolkit::plugins()` to your own `RichContentRenderer` and render it with `RichEditorToolkit::toHtml($renderer)` (its own `toHtml()` uses Filament's shared sanitizer, which the toolkit never extends). Per-field `CustomAttributesPlugin::make()->attributes([...])`/`->types([...])` must be repeated in `RichEditorToolkit::renderer($content, attributes: [...], types: [...])`. `PasteCleanPlugin` has NO server half and must NOT be added to the renderer (a second pass would strip the attributes the other plugin keeps).
- Attribute allow-list = `class`, `id`, `style` + `rich-editor-toolkit.attributes` config (explicit names; Symfony's sanitizer has no `data-*` wildcard). `on*`, URL attributes (`href`, `src`, `srcset`, `srcdoc`, `action`, `formaction`, ...), `is`, names with `:` and framework directives (`x-*`, `hx-*`, `v-*`, `ng-*`, `wire:*`) are never accepted; list only what you need (`data-*`, `aria-*`, `role`). Node types missing from the built-in list: `rich-editor-toolkit.types`. The PHP list (`Extensions\CustomAttributes::TYPES`) and `resources/js/src/custom-attributes.js` `DEFAULT_TYPES` must stay identical (a test pins it).
- Embeds: YouTube/Vimeo links are parsed by `Support\VideoEmbed` and rebuilt (youtube-nocookie, no autoplay); other hosts need `rich-editor-toolkit.embed.hosts` (`host` or `host/path/prefix`, https only, prefix matched on a segment boundary, dot segments refused). The `src` is checked when HTML is parsed AND when a node is rendered (JSON content). `sandbox`/`allow`/`referrerpolicy`/`loading` are forced on render.
- Rebuild the JS after editing `resources/js/src/*`: `npm run build` (commit `resources/dist`), test with `npm run test:js`.
